### PR TITLE
Improve LoopHelper.loop_sleep() accuracy

### LINKED ISSUE #5: LoopHelper FPS limiter lags if work is done outside of loop
`spin_sleep::LoopHelper` is designed wrong. It doesn't use the end `loop_sleep()` of the previous frame to time the end of the next frame... but uses the beginning `loop_start()` of the next frame (which is a different Instant).

I have a app using Winit to create a GUI. It renders frames in `Event::MainEventsCleared`, using wgpu in PresentMode::Immediate (no vsync). I'm trying to throttle the frame rendering rate using LoopHelper.

When I set the target FPS to 250, I get 220 in practice. When I set the target FPS to 200, I get 180 in practice. This is because winit does work between callback/render iterations.

If I move `loop_sleep()` to right before `loop_start()` (contrary to what the example code does), I get 198 FPS, which is still systematically lower than 200.

The code causing this is this variable and its usages:

https://github.com/alexheretic/spin-sleep/blob/929eef77f8282998cc33addb26de406d54c53427/src/loop_helper.rs#L46

Not sure how to program it. If the rendering is faster than the target FPS (the limiter is sleeping), each `loop_sleep()`'s "target endpoint" should be exactly `target_delta` after the previous frame's "target endpoint", rather than the `Instant` returned after the previous frame's sleep ends or when the current frame begins. If the rendering is slower than the target FPS (each frame takes longer than `target_delta`), then you need to use the `Instant` returned after the previous frame's sleep is called. But I don't know if you can distinguish these cases.

Basically I'm trying to recreate `setInterval()` but synchronously via thread blocking, rather than as a callback. I may fork spin-sleep and try to implement the API myself. Or I might use winit timers instead (https://github.com/rust-windowing/winit/blob/master/examples/timer.rs). Don't know which to pick, tbh.

### PR DESCRIPTION
**Pull request by nyanpasu64**
Previously, it would ensure that the correct interval passed between `loop_start()` being called, and `loop_sleep()` returning. Now, it ensures that all calls to `loop_sleep()` return at globally uniform intervals, but falls back to comparing adjacent function calls if the FPS drops below the target even without the limiter on.

This also improves the accuracy of the first `report_rate()` measurement (the first loop_start() call no longer computes a delta from `build_with_target_rate()`).

Fixes #5.

## Motivation

Issue #5:

> When I set the target FPS to 250, I get 220 in practice. When I set the target FPS to 200, I get 180 in practice. This is because winit does work between callback/render iterations.
> 
> If I move `loop_sleep()` to right before `loop_start()` (contrary to what the example code does), I get 198 FPS, which is still systematically lower than 200.

After this PR, the FPS measurements remain within 0.1 fps of 200, excluding the first FPS measurement (warm-up time).

## Failing Tests

The tests (`rate_reporting_using_duration` and `rate_reporting_using_seconds`) fail. I don't know how to make them pass, because I think the API they test is wrong.

https://github.com/alexheretic/spin-sleep/blob/753b9002540e47bf74c00f8e51aa6b13212b373f/src/loop_helper.rs#L202-L207

`deltas[0]` does not reflect the duration of `sleep()`, but rather how long it takes to initialize `loops`, create a `vec![]` with no allocation, and create an `Instant`. If you want to measure 10 deltas, I'd add a dummy `loop_start()` call after the loop ends.

## Redesigning the API

TBH I think the current API is bad, and the delta should be returned by an "end loop" function, with`loop_start()` being removed completely Perhaps add 3 functions:

- `loop_sleep() -> ()` is implemented much like my current PR. It can skip calling `Instant::now()` if FPS is above the limit and `sleep()` was called.
- `loop_sleep_get_delta() -> Duration` must always call `Instant::now()` to compute the return value.
- `loop_end() -> Duration` does not sleep, and only calls `Instant::now()`.

I suspect that splitting `loop_sleep_get_delta` into a separate function (so `loop_sleep` sometimes but not always skips `Instant::now()` which locks a StaticMutex) is not a worthwhile optimization.

Also to match the current API, we need `loop_sleep_no_spin` variants of the first 2 functions as well. So if we keep `_get_delta` as a separate function, that's 4 different functions for ending a frame, which seems too much.

### Fixing `report_rate()`

If we remove `loop_start()` and remove `last_loop_start`, it can no longer be used for computing `report_rate()`. We can have `loop_sleep()` compute deltas using `last_loop_end` (which may be inaccurate because I use `+=` rather than `Instant::now()`), a second variable holding `Instant::now()` instead of the "idealized" loop end, or not at all (instead `report_rate()` calls `Instant::now()` itself).

----

TBH I don't fully understand the design space myself. I'd have to implement a redesigned API in a fork (and I don't know if my changes would be accepted upstream).

Looking at Minecraft's frame-time meter, another possible API is "begin work" and "end work" methods, which only measure rendering work, not time spent sleeping. However I wouldn't add them to LoopHelper, since they would work as freestanding functions, the first returning `Instant` and the second accepting it.

### CODE REVIEW

**Comment by nyanpasu64** [comment]
Corrections:

- `self.last_loop_end.elapsed()` already calls `Instant::now()` internally. Calling it again is unnecessary.
- I removed `loop_sleep_get_delta()` in my fork, since I don't need it. But it would be fairly easy to add the return value (though it might be faked to some extent).
- I made `report_rate()` depend on `last_loop_end`, and removed all calls to `Instant::now()` because it was the simplest solution.

**Comment by nyanpasu64** [comment]
My own design has further diverged from this. I've changed the API in incompatible ways, but haven't rewritten the tests yet.

My current code is at https://github.com/nyanpasu64/spectro2/blob/8314b93d23408f12ddef595d5cf6638e8247797e/3rdparty/spin_sleep-1.0.0/src/loop_helper.rs .

**Comment by DavJCosby** [comment]
Wish this was merged in. Current timing strategy is consistently wrong while this one does the trick.

Can we get this re-opened and merged in so #5 can finally get fixed?

| Target Refresh Rate | Avg Reported Rate<br>(spin_sleep 1.1.1) | Avg Reported Rate<br>(This PR) |
| ---- | ---- | ---- |
| 90 | 75.26 | 89.96 |
| 120 | 99.46 | 120.95 |
| 250 | 210.38 | 249.98 |
| 900 | 802.75 | 899.97 |

```rust
loop {
    let _delta = self.loop_helper.loop_start();

    if let Some(fps) = self.loop_helper.report_rate() {
        println!("{}", fps);
    }

    self.loop_helper.loop_sleep()
}
```

**Comment by alexheretic** [comment]
I think we left #5 off at proposing a non-breaking new api rather than changing the existing one. This can also be done outside of this crate, my current preference. See https://github.com/alexheretic/spin-sleep/issues/5#issuecomment-1869884926

Perhaps a new crate providing something like a sync tokio `Interval` with a similarly configurable missed tick behaviour using this crate to sleep.

**Pull request closed without merging**
